version: "3.7"
services:
  app:
    build: .
    ports:
      - "${APP_EXTERNAL_PORT}:${APP_INTERNAL_PORT}"
    volumes:
      - ./content/files:${APP}/content/files
  mysql:
    image: "mysql:latest"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}"
    volumes:
      - ./content/db:/var/lib/mysql
