version: "3.7"
services:
  web:
    build: .
    ports:
      - "${WEB_PORT}:8080"
    volumes:
      - ./content/files:${APP}/content/files
  mysql:
    image: "mysql:latest"
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./content/db:/var/lib/mysql
