version: '3'
services:
  web:
    build: '.'
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  mysql:
    image: "mysql:alpine"
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
