version: "3.3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./content/:/app/gongmo/content/
  mysql:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
