version: "3.3"
services:
  web:
    build: .
    ports:
      - "${WEB_PORT}:8080"
    volumes:
      - ./content/files:${APP}/content/files
  mysql:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
